name: Release VS Code Extension

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package VS Code Extension
        run: |
          npx vsce package
          mkdir -p release
          mv *.vsix release/commitmate-${GITHUB_REF_NAME}.vsix

      - name: Upload VSIX as artifact
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: release/*.vsix
