name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Package VSIX
        run: npx vsce package

      - name: List files
        run: ls -l

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: commitmate-*.vsix
