name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Inject GA secrets
        run: |
          echo "export const GA_MEASUREMENT_ID = '${{ secrets.GA_MEASUREMENT_ID }}';" > src/analyticsSecrets.ts
          echo "export const GA_API_SECRET = '${{ secrets.GA_API_SECRET }}';" >> src/analyticsSecrets.ts

      - name: Package VSIX
        run: npx vsce package

      - name: List files
        run: ls -l

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: commitmate-*.vsix

      - name: Publish to VS Code Marketplace
        run: npx @vscode/vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
